# Generated by Django 3.1.2 on 2020-10-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='1.1.1.1', max_length=32)),
                ('hostname', models.CharField(default='unknown', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='df -h', max_length=1024)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.host')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='myroot', max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.host')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(null=True, verbose_name='begin timea')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end time')),
                ('res', models.IntegerField(default=9999)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.method')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.user'),
        ),
    ]
