# Generated by Django 3.1.2 on 2020-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='begin_time',
            field=models.DateTimeField(null=True, verbose_name='begin time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='res',
            field=models.IntegerField(default=4399),
        ),
    ]
