# Generated by Django 3.1.2 on 2020-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20201115_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowmethodmembership',
            options={'ordering': ['method', 'rank']},
        ),
        migrations.AddField(
            model_name='flowmethodmembership',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowmethodmembership',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
