# Generated by Django 3.1.2 on 2020-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_method_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
