# Generated by Django 3.1.2 on 2020-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20201108_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['begin_time']},
        ),
        migrations.AddField(
            model_name='method',
            name='expect_res',
            field=models.IntegerField(default=4398),
        ),
    ]
